Versioning debug - 2

diff --git a/.github/workflows/valery_scan.yaml b/.github/workflows/valery_scan.yaml
--- a/.github/workflows/valery_scan.yaml
+++ b/.github/workflows/valery_scan.yaml
@@ -21,7 +21,7 @@ jobs:
 
       - uses: snyk/actions/setup@master
       - name: Scan
-        run: | 
+        run: |
           touch result.txt
           echo "snyk test results:" > result.txt
           readarray -t imageslist < docker_images.txt
@@ -29,15 +29,20 @@ jobs:
           for image_name in "${imageslist[@]}"; do
             echo "$image_name: " >> result.txt
             snyk container test  $image_name  --severity-threshold=high --json-file-output=snyk.json || true
+            if [[ ! -s snyk.json ]]; then
+              echo "Error: snyk.json is empty or does not exist"
+              echo "Contents of snyk.json:"
+              cat snyk.json
+              exit 1
+            fi
             echo "print snyk:"
             jq ' .summary   ' snyk.json  | sed 's|[",]||g' >> result.txt
-            jq ' .vulnerabilities[] | {id,title,severity} ' snyk.json | while read vulnerability; do
-              vulnerability_id=$(echo $vulnerability | jq -r '.id')
-              echo "- Vulnerability: $(echo $vulnerability | jq -r '.title') (Severity: $(echo $vulnerability | jq -r '.severity'))"
-              echo "  Link: https://snyk.io/vuln/$vulnerability_id"
-            done >> result.txt
+            jq ' .vulnerabilities[] | {id,title,severity} ' snyk.json  >> result.txt
+            echo "Result txt:"
+            cat result.txt
           done
           cat result.txt | sed 's|[{"},]||g' > final_result.txt
+
 
       - name: Update snyk result as pr comment
         uses: thollander/actions-comment-pull-request@v2
